libflash: Set SKIBOOT_VERSION for host-libflash
The recent change to install host-pflash can cause the build to fail
since PFLASH_VERSION is not set:

version.c:1:2: error: #error You need to set PFLASH_VERSION environment variable
 #error You need to set PFLASH_VERSION environment variable
  ^
rules.mk:39: recipe for target 'version.o' failed

PFLASH_VERSION is set from SKIBOOT_VERSION, add it to the build command
as we do for normal libflash build command.

Signed-off-by: Samuel Mendoza-Jonas <sam@mendozajonas.com>