skiboot: Use host-openssl
The create-container host utility in skiboot is currently being built
against the system ssl installation instead of the buildroot one, as
exposed by broken builds on machines that do not have openssl-devel
installed:

  [ HOSTCC ] libstb/create-container.c
  libstb/create-container.c:10:10: fatal error: openssl/bn.h: No such file or directory

To fix, ensure that the skiboot build is using host-openssl.

Signed-off-by: Reza Arbab <arbab@linux.ibm.com>
(cherry picked from commit d06b647f8607142e2d479ff48806acc101c6acc5)